default: &default
  adapter: postgresql

development:
  <<: *default
  database: rails-template-01-development

test:
  <<: *default
  database: rails-template-01-test

production:
  <<: *default
  database: rails-template-01-production
